no, make is cool

diff --git a/bin/TSDBTruncate b/bin/TSDBTruncate
--- a/bin/TSDBTruncate
+++ b/bin/TSDBTruncate
@@ -2,7 +2,7 @@
 
 script=$(basename ${BASH_SOURCE[0]})
 class=${script}.class
-hbcp=$(hbase classpath)
+export hbcp=$(hbase classpath)
 if [[ -z $hbcp ]]; then
   echo "Couldn't load HBase classpath" >&2
   exit 1
@@ -12,13 +12,10 @@ rootdir=$(dirname $bindir)
 srcdir=$rootdir/src
 src=$srcdir/${script}.java
 
-
-if [[ ! -e $bindir/$class ]]; then
-  javac -cp $hbcp -d $bindir $src
-  if [[ $? -ne 0 ]]; then
-    echo "Failed to compile" >&2
-    exit 1
-  fi
+make -C $rootdir bin/${script}.class
+if [[ $? -ne 0 ]]; then
+  echo "Failed to compile" >&2
+  exit 1
 fi
 
 java -cp $hbcp:$bindir $script "$@"
